# Generated by Django 4.1.7 on 2023-04-13 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_rename_notifcations_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
