# Generated by Django 4.1.7 on 2023-04-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notifications_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notifications", options={"ordering": ("-created_at",)},
        ),
    ]
