# Generated by Django 4.1.7 on 2023-04-04 22:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='avaliable_to_reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(max_length=200)),
                ('end_date', models.DateTimeField(max_length=200)),
                ('property_id', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DENIED', 'DENIED'), ('APPROVED', 'APPROVED'), ('CANCELLED', 'CANCELLED'), ('TERMINATED', 'TERMINATED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
