# Generated by Django 4.1.2 on 2023-04-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_avaliable_to_reserve_property_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
