# Generated by Django 4.1.7 on 2023-04-14 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_alter_property_options_property_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservationrequest", options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="reservationrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
