# Generated by Django 4.1.2 on 2023-04-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_reservationrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('property_id', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
